services:
  hytale:
    container_name: hytale-server
    build: .
    restart: unless-stopped
    # stdin_open: true
    # tty: true
    ports:
      - "5520:5520/udp"
    volumes:
      - ./server:/hytale
    environment:
      JAVA_OPTS: "-Xms2G -Xmx4G"
      AOT_OPTS: "-XX:AOTCache=HytaleServer.aot"
    deploy:
      resources:
        limits:
          memory: 6G
